[program:airoxy]
process_name=%(program_name)s
command=php /var/www/airoxy/artisan airoxy:serve
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/airoxy/airoxy.log
stopwaitsecs=30

[program:airoxy-scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while true; do php /var/www/airoxy/artisan schedule:run --no-interaction >> /dev/null 2>&1; sleep 60; done"
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/airoxy/scheduler.log
stopwaitsecs=10
